0.36.0-2: p_wifi: add admin administrator, set flag nojoin on installation

diff --git a/debian/linuxmuster-schulkonsole.postinst b/debian/linuxmuster-schulkonsole.postinst
--- a/debian/linuxmuster-schulkonsole.postinst
+++ b/debian/linuxmuster-schulkonsole.postinst
@@ -122,10 +122,14 @@ case "$1" in
 	    admin="$(sophomorix-project -p p_wifi -i|cut -d\| -f3|grep administrator| tr -d '[[:space:]]')"
 	    nojoin="$(sophomorix-project -p p_wifi -i|cut -d\| -f2|grep '^Joinable'|cut -d\: -f2|grep '0' | tr -d '[[:space:]]')"
 	    if [ ! "${admin}" = "administrator" ]; then
-		echo "    --> Please add user administrator to wlan project ${wlan_ldap_group}! <--"
+		echo -n "    adding admin administrator to wlan project ${wlan_ldap_group}..."
+		sophomorix-project -p ${wlan_ldap_group} --addadmins administrator >/dev/null 2>/dev/null \
+		    && echo "Done." || echo "Failed."
 	    fi
 	    if [ ! "${nojoin}" = "0" ]; then
-		echo "    --> Please set flag --nojoin for wlan project ${wlan_ldap_group}! <--"
+		echo -n "    setting flag --nojoin for wlan project ${wlan_ldap_group}..."
+		sophomorix-project -p ${wlan_ldap_group} --nojoin >/dev/null 2>/dev/null \
+		    && echo "Done." || echo "Failed."
 	    fi
 	fi
 
